@echo off
REM ****************************************************************************
REM Vivado (TM) v2017.3 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
<<<<<<< HEAD
REM Generated by Vivado on Mon Dec 04 05:54:06 -0500 2017
REM SW Build 2035080 on Fri Oct 20 14:20:01 MDT 2017
=======
REM Generated by Vivado on Mon Dec 04 04:22:06 -0500 2017
REM SW Build 2018833 on Wed Oct  4 19:58:22 MDT 2017
>>>>>>> 30880b11b88e631477dbd5cdd3c2ce24c9637e85
REM
REM Copyright 1986-2017 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
call xsim Multimedia_Processor_tb_behav -key {Behavioral:Multimedia_Processor_tb:Functional:Multimedia_Processor_tb} -tclbatch Multimedia_Processor_tb.tcl -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
